---
title: "Instacart"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(plyr)
library(ggplot2)
library(tidyr)
library(arules)
library(arulesViz)

#set directory
setwd("~/Dropbox/Data Science/Instacart")


files <- c("aisles","departments","order_products__prior","order_products__train","orders","products")

for (i in 1:length(files)){
  assign(files[i], read.csv(paste(files[i],".csv",sep = "")))
  
}

```


#Joining the tables
```{r, echo=FALSE}
order_join <- products %>% merge(., aisles, by = "aisle_id", all.x = TRUE) %>%
  merge(., departments, by="department_id", all.x= TRUE) %>%
  merge(order_products__train, ., by = "product_id",all.x = TRUE) %>%
  merge(., orders, by = "order_id", all.x = TRUE)


#order_join2 <- products %>% merge(., aisles, by = "aisle_id", all.x = TRUE) %>%
#  merge(., departments, by="department_id", all.x= TRUE) %>%
#  merge(order_products__prior, ., by = "product_id",all.x = TRUE) %>%
#  merge(., orders, by = "order_id", all.x = TRUE)

orders_train <- order_join[which(order_join$eval_set == "train"),]

clean <- c("department_id","aisle_id","eval_set")
orders_train <- orders_train[,!names(orders_train) %in% clean]

```


#Reordered products versus product type 
```{r, echo=FALSE}
orders_train %>%
  ddply(., "department",summarise,total_trans=length(order_id),
        perc_reorder=length(which(reordered==1))/length(order_id)) %>% 
  ggplot(., aes(x = total_trans, y = perc_reorder,label = department)) + 
  geom_text()

```

```{r, echo = FALSE}
orders_train %>% 
  ddply(., c("product_id","order_hour_of_day"),summarize, N= length(unique(order_id))) %>%
  ggplot(., aes(x = order_hour_of_day, y = N,group = product_id, color = product_id)) + 
  geom_line()

```


```{r, echo = FALSE}
orders_train %>% 
  ddply(., c("product_id","order_dow"),summarize, N= length(unique(order_id))) %>%
  ggplot(., aes(x = order_dow, y = N,group = product_id, color = product_id)) + 
  geom_line()

```


```{r, echo = FALSE}
orders_train %>%
  ddply(., c("product_id","order_dow","order_hour_of_day"),summarize,
                       N = length(unique(order_id))) %>%
  ggplot(., aes(x = product_id, y = N)) + 
  geom_point(aes(color = order_hour_of_day))

```

#Percentage of Users that reorder products and days since last order
```{r, echo = FALSE}

orders_train %>%
  ddply(., "user_id" ,summarize, 
                      perc_reorder = length(which(reordered == 1))/length(order_id)) -> a

cuts <- cut(a$perc_reorder, seq(0,1,0.1),include.lowest = TRUE)
cuts <-as.data.frame(cuts)
cuts <- ddply(cuts, "cuts",summarize, n = length(cuts))

ggplot(cuts, aes(x =cuts , y = n)) + geom_bar(stat = "identity") + 
  labs(x = "% Reorders", y = "Number of Users")

orders_train %>%
  mutate(days_since = as.factor(days_since_prior_order)) %>%
  ddply(., "days_since", summarize, N= length(user_id))%>%
  ggplot(., aes(x = days_since, y = N)) + geom_bar(stat = "identity", fill = "red")

```

#Association Rules Viz on Order Data

```{r, echo=FALSE}
#######Association Rules###############

#first five products in cart
cart_products <- function(n,data){
  number <- seq(1,n,1)
  ordered_firstn <- data[data$add_to_cart_order %in% number,]
  sort_data <- ordered_firstn[order(ordered_firstn$order_id,ordered_firstn$add_to_cart_order),]
  return(sort_data)
}


#aggregate data for each user

text2vec <- function(n, data, by, with){
  text_data <- cart_products(n,data)
  text_data$product_name <- gsub(",","",text_data[,with])
  product_user <- aggregate(as.formula(paste(with,by, sep = " ~ ")), data = text_data, paste, collapse = ",")
  text <- as.character(product_user[,with])
  text <- strsplit(text, ",")
  maxLen <- max(sapply(text, length))
  text <- t(sapply(text, function(x) c(x, rep(NA, maxLen - length(x)))))
  text <- as.data.frame(text)
  return(text)
}

text = text2vec(84, orders_train, by = "order_id", with = "product_name")
rules <- apriori(text, parameter = list(minlen = 2,  conf = 0.7, supp= 0.00003, maxtime = 100000000))
rules.sorted <- sort(rules, by="lift")
inspectDT(rules.sorted)
```

